#!/bin/sh

set -e

ARCH=""
VERBOSE=false
CLEAN=false
RELEASE=false

usage() {
    cat << EOF
UNIX V11 Build System

Usage: $0 <arch|-h> [options]

Architectures:
    AMD64    (alias: x86-64, x64)
    AArch64  (alias: Arm64)
    -h       Show this help

Options:
    -r           Release build
    -clean       Clean before building
    -v           Verbose output

Examples:
    $0 amd64
    $0 aarch64 -clean

EOF
    exit 0
}

to_lower() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

if [ $# -eq 0 ]; then
    echo "Error: Architecture not specified"
    echo "Use '$0 -h' for usage information"
    exit 1
fi

ARCH=`to_lower "$1"`
case $ARCH in
    -h)
        usage
        ;;
    aarch64|arm64)
        EFI_TARGET="aarch64-unknown-uefi"
        KERNEL_TARGET="aarch64-unknown-none"
        EFI_BOOT_NAME="bootaa64.efi"
        ;;
    amd64|x86-64|x86_64|x64)
        EFI_TARGET="x86_64-unknown-uefi"
        KERNEL_TARGET="x86_64-unknown-none"
        EFI_BOOT_NAME="bootx64.efi"
        ;;
    *)
        echo "Error: Unknown architecture: $ARCH"
        echo "Use '$0 -h' for usage information"
        exit 1
        ;;
esac

shift

while [ $# -gt 0 ]; do
    case `to_lower "$1"` in
        -r)
            RELEASE=true
            ;;
        -clean)
            CLEAN=true
            ;;
        -v)
            VERBOSE=true
            ;;
    esac

    shift
done

rm -rf dist

if [ "$CLEAN" = "true" ]; then
    if [ "$VERBOSE" = "true" ]; then
        cargo clean
    else
        cargo clean -q
    fi
fi

BUILD_ARGS=""

if [ "$RELEASE" = "true" ]; then
    BUILD_ARGS="-r"
fi
if [ "$VERBOSE" = "false" ]; then
    BUILD_ARGS="$BUILD_ARGS -q"
fi

cd efi
cargo build --target $EFI_TARGET $BUILD_ARGS
cd ..

cd kernel
cargo build --target $KERNEL_TARGET $BUILD_ARGS
cd ..

mkdir -p dist/efi/boot

EFI_TARGET_DIR=`echo "$EFI_TARGET" | sed 's/\.json$//' | sed 's/.*\///'`
KERNEL_TARGET_DIR=`echo "$KERNEL_TARGET" | sed 's/\.json$//' | sed 's/.*\///'`

BUILD_DIR=""
if [ "$RELEASE" = "true" ]; then
    BUILD_DIR="release"
else
    BUILD_DIR="debug"
fi


cp target/$EFI_TARGET_DIR/$BUILD_DIR/unix-v11-efi.efi dist/efi/boot/$EFI_BOOT_NAME
cp target/$KERNEL_TARGET_DIR/$BUILD_DIR/unix-v11-kernel dist/unix
echo System ready: dist
