#!/bin/sh

set -e
PRJCT_ROOT=`cd \`dirname "$0"\`/.. && pwd`

ARCH=""
VERBOSE=0
CLEAN=false
RELEASE=false

usage() {
    cat << EOF
UNIX V11 Build System

Usage: $0 <arch|-h> [options]

Architectures:
    AArch64 (alias: Arm64, Armv8, Armv8a, Armv8-A)
    AMD64   (alias: x86-64, x64)
    -h      Show this help

Options:
    -r      Release build
    -c      Clean before building
    -v      Verbose output
    -V      Verbose output including compiler warnings

Examples:
    $0 amd64 -r -v
    $0 aarch64 -cV

EOF
    exit 0
}

to_lower() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

die() {
    echo "Error: $1"
    echo "Use '$0 -h' for usage information"
    exit 1
}

if [ $# -eq 0 ]; then
    die "Architecture not specified"
fi

ARCH=`to_lower "$1"`
case $ARCH in
    -h)
        usage
        ;;
    aarch64|arm64|armv8|armv8a|armv8-a)
        EFI_TARGET="aarch64-unknown-uefi"
        KERNEL_TARGET="aarch64-unknown-none"
        EFI_BOOT_NAME="bootaa64.efi"
        ;;
    amd64|x86-64|x86_64|x64)
        EFI_TARGET="x86_64-unknown-uefi"
        KERNEL_TARGET="x86_64-unknown-none"
        EFI_BOOT_NAME="bootx64.efi"
        ;;
    *)
        die "Unknown architecture: $ARCH"
        ;;
esac

shift

while [ $# -gt 0 ]; do
    case "$1" in -*r*) RELEASE=true ;; esac
    case "$1" in -*c*) CLEAN=true   ;; esac
    case "$1" in -*v*) VERBOSE=1    ;; esac
    case "$1" in -*V*) VERBOSE=2    ;; esac
    shift
done

if [ "$CLEAN" = "true" ]; then
    if [ "$VERBOSE" = "0" ]; then
        cargo clean -q
    else
        cargo clean
    fi
fi

BUILD_ARGS=""

if [ "$RELEASE" = "true" ]; then
    BUILD_ARGS="-r"
fi
if [ "$VERBOSE" = "0" ]; then
    BUILD_ARGS="$BUILD_ARGS -q"
fi

BUILD_ARGS="$BUILD_ARGS --"

case "$VERBOSE" in
    0|1) BUILD_ARGS="$BUILD_ARGS -A warnings" ;;
esac

cd $PRJCT_ROOT/efi
cargo rustc --target $EFI_TARGET $BUILD_ARGS

cd $PRJCT_ROOT/kernel
cargo rustc --target $KERNEL_TARGET $BUILD_ARGS

cd $PRJCT_ROOT/corecli/aleph
cargo rustc --target $KERNEL_TARGET $BUILD_ARGS

cd $PRJCT_ROOT

rm -rf "$PRJCT_ROOT/udisk"
mkdir -p "$PRJCT_ROOT/udisk"
mkdir -p "$PRJCT_ROOT/udisk/efi/boot"
mkdir -p "$PRJCT_ROOT/udisk/sbin"

EFI_TARGET_DIR=`echo "$EFI_TARGET" | sed 's/\.json$//' | sed 's/.*\///'`
KERNEL_TARGET_DIR=`echo "$KERNEL_TARGET" | sed 's/\.json$//' | sed 's/.*\///'`

BUILD_DIR=""
if [ "$RELEASE" = "true" ]; then
    BUILD_DIR="release"
else
    BUILD_DIR="debug"
fi

cp "$PRJCT_ROOT/target/$EFI_TARGET_DIR/$BUILD_DIR/unix-v11-efi.efi" "$PRJCT_ROOT/udisk/efi/boot/$EFI_BOOT_NAME"
cp "$PRJCT_ROOT/target/$KERNEL_TARGET_DIR/$BUILD_DIR/unix-v11-kernel" "$PRJCT_ROOT/udisk/unix"
cp "$PRJCT_ROOT/target/$KERNEL_TARGET_DIR/$BUILD_DIR/unix-v11-aleph" "$PRJCT_ROOT/udisk/sbin/aleph"
echo System ready: udisk
