#!/bin/sh

set -e
PRJCT_ROOT=`cd \`dirname "$0"\`/.. && pwd`

DISK_NAME=unix.disk
DISK_SIZE=64

usage() {
    cat << EOF
UNIX V11 Imaging System

Usage: $0 <disk name> <disk size>

Disk name:
    Name of disk image [default: unix.disk]
    \`-h\` will be considered as help flag, please use ./-h instead.

Disk size:
    Disk size in MiB [default: 64 MiB]

Examples:
    $0
    $0 hanabi.img 256
    $0 dmr\&klt.disk 524288

EOF
    exit 0
}

if [ $# -gt 0 ]; then
    DISK_NAME=$1
    if [ $# -gt 1 ]; then
        DISK_SIZE=$2
    fi
fi

if [ $DISK_NAME = "-h" ]; then
    usage
fi

dd if=/dev/zero of=$DISK_NAME bs=1M count=$DISK_SIZE status=none 2>/dev/null || \
dd if=/dev/zero of=$DISK_NAME bs=1m count=$DISK_SIZE status=none

if [ "`uname`" = "Darwin" ]; then
    diskno=`hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount $DISK_NAME | head -n 1 | awk '{print $1}'`
    diskutil eraseDisk FAT32 UNIXV11EFI GPTFormat $diskno > /dev/null
    cp -R $PRJCT_ROOT/udisk/* /Volumes/UNIXV11EFI/
    hdiutil detach $diskno > /dev/null
else
    LOOP_DEV=`sudo losetup -f --show $DISK_NAME`
    sudo parted -s $LOOP_DEV mklabel gpt
    sudo parted -s $LOOP_DEV mkpart primary fat32 1MiB 100%
    sudo mkfs.vfat -n UNIXV11EFI ${LOOP_DEV}p1 > /dev/null

    MOUNT_DIR=`mktemp -d`
    sudo mount ${LOOP_DEV}p1 $MOUNT_DIR
    sudo cp -R $PRJCT_ROOT/udisk/* $MOUNT_DIR/
    sudo umount $MOUNT_DIR
    rmdir $MOUNT_DIR
    sudo losetup -d $LOOP_DEV
fi

echo "Disk ready: $DISK_NAME"
