#!/bin/sh

set -e
PRJCT_ROOT=`cd \`dirname "$0"\`/.. && pwd`

ARCH=""
DISK_NAME="unix.disk"
RAM_SIZE=512
CPU_COUNT=1

usage() {
    cat << EOF
UNIX V11 Simulator

Usage: $0 <arch> [options]

Architectures:
    AMD64    (alias: x86-64, x64)
    AArch64  (alias: Arm64)
    -h       Show this help

Options:
    -disk <path> Disk image location [default: unix.disk]
    -ram <size>  RAM size in MiB [default: 512 MiB]
    -cpu <count> CPU count [default: 1]

Examples:
    $0 amd64
    $0 aarch64 -ram 8192 -cpu 4
    $0 arm64 -cpu 8 system.img
    $0 x86-64 -disk unix-amd64.disk

EOF
    exit 0
}

to_lower() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

if [ $# -eq 0 ]; then
    echo "Error: Architecture not specified"
    echo "Use '$0 -h' for usage information"
    exit 1
fi

ARCH=`to_lower "$1"`
FW_DIR="firmwares"
case $ARCH in
    -h)
        usage
        ;;
    aarch64|arm64)
        QEMU_SYSTEM="qemu-system-aarch64"
        QEMU_CPU="cortex-a72"
        QEMU_MACHINE="virt,accel=tcg"
        EFI_CODE="OVMF-AArch64-CODE.fd"
        EFI_VARS="OVMF-AArch64-VARS.fd"
        ;;
    amd64|x86-64|x86_64|x64)
        QEMU_SYSTEM="qemu-system-x86_64"
        QEMU_CPU="qemu64"
        QEMU_MACHINE="q35,accel=tcg"
        EFI_CODE="OVMF-AMD64-CODE.fd"
        EFI_VARS="OVMF-AMD64-VARS.fd"
        ;;
    *)
        echo "Error: Unknown architecture: $ARCH"
        echo "Use '$0 -h' for usage information"
        exit 1
        ;;
esac

if [ ! -f "$PRJCT_ROOT/$FW_DIR/$EFI_CODE" ] || [ ! -f "$PRJCT_ROOT/$FW_DIR/$EFI_VARS" ]; then
    mkdir -p $PRJCT_ROOT/$FW_DIR
    uncompress < $PRJCT_ROOT/OVMF.pax.Z | (cd $PRJCT_ROOT/$FW_DIR && pax -r)
fi

shift

while [ $# -gt 0 ]; do
    case `to_lower "$1"` in
        -disk)
            if [ -z "$2" ] || [ "$(echo "$2" | cut -c1)" = "-" ]; then
                echo "Error: -disk requires a path argument"
                if [ "$(echo "$2" | cut -c1)" = "-" ]; then
                    echo "If the disk name starts with a dash, please consider \`./\` prefix."
                fi
                exit 1
            fi
            DISK_NAME="$2"
            shift
            ;;
        -ram)
            if [ -z "$2" ] || [ "$(echo "$2" | cut -c1)" = "-" ]; then
                echo "Error: -ram requires a size argument"
                exit 1
            fi
            RAM_SIZE="$2"
            shift
            ;;
        -cpu)
            if [ -z "$2" ] || [ "$(echo "$2" | cut -c1)" = "-" ]; then
                echo "Error: -cpu requires a count argument"
                exit 1
            fi
            CPU_COUNT="$2"
            shift
            ;;
    esac

    shift
done

$QEMU_SYSTEM \
    -cpu $QEMU_CPU \
    -machine $QEMU_MACHINE \
    -smp $CPU_COUNT \
    -drive if=pflash,file=$PRJCT_ROOT/$FW_DIR/$EFI_CODE,format=raw,readonly=on \
    -drive if=pflash,file=$PRJCT_ROOT/$FW_DIR/$EFI_VARS,format=raw \
    -drive file=$DISK_NAME,if=none,id=drv0,format=raw \
    -device nvme,drive=drv0,serial=unixv11nvme \
    -m ${RAM_SIZE}M \
    -serial stdio
