#!/bin/sh

set -e
PRJCT_ROOT=`cd \`dirname "$0"\`/.. && pwd`

ARCH=""
DISK_NAME="unix.disk"
RAM_SIZE=512
CPU_COUNT=1

usage() {
    cat << EOF
UNIX V11 Simulator

Usage: $0 <arch> [options]

Architectures:
    AArch64  (alias: Arm64, Armv8, Armv8a, Armv8-A)
    AMD64    (alias: x86-64, x64)
    -h       Show this help

Options:
    -i <path>  Disk image location [default: unix.disk]
    -p <count> CPU count [default: 1]
    -r <size>  RAM size in MiB [default: 512 MiB]

Examples:
    $0 amd64
    $0 aarch64 -r 8192 -p 4
    $0 arm64 -p 8 -i system.img
    $0 x86-64 -i unix-amd64.disk

EOF
    exit 0
}

to_lower() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

is_uint() {
    case "$1" in
        ''|*[!0-9]*) return 1 ;;
        *) return 0 ;;
    esac
}

die() {
    echo "Error: $1"
    echo "Use '$0 -h' for usage information"
    exit 1
}

if [ $# -eq 0 ]; then
    die "Architecture not specified"
fi

ARCH=`to_lower "$1"`
FW_DIR="firmwares"
case $ARCH in
    -h)
        usage
        ;;
    aarch64|arm64|armv8|armv8a|armv8-a)
        QEMU_SYSTEM="qemu-system-aarch64"
        QEMU_CPU="cortex-a72"
        QEMU_MACHINE="virt,accel=tcg"
        EFI_CODE="OVMF-AArch64-CODE.fd"
        EFI_VARS="OVMF-AArch64-VARS.fd"
        ;;
    amd64|x86-64|x86_64|x64)
        QEMU_SYSTEM="qemu-system-x86_64"
        QEMU_CPU="qemu64"
        QEMU_MACHINE="q35,accel=tcg"
        EFI_CODE="OVMF-AMD64-CODE.fd"
        EFI_VARS="OVMF-AMD64-VARS.fd"
        ;;
    *)
        die "Unknown architecture: $ARCH"
        ;;
esac

if [ ! -f "$PRJCT_ROOT/$FW_DIR/$EFI_CODE" ] || [ ! -f "$PRJCT_ROOT/$FW_DIR/$EFI_VARS" ]; then
    mkdir -p "$PRJCT_ROOT/$FW_DIR"
    uncompress < "$PRJCT_ROOT/OVMF.pax.Z" | (cd "$PRJCT_ROOT/$FW_DIR" && pax -r)
fi

shift

while [ $# -gt 0 ]; do
    case "$1" in
        -i)
            if [ -z "$2" ] || [ `echo "$2" | cut -c1` = "-" ]; then
                die_msg="-i requires a path argument"
                [ -n "$2" ] && die_msg="$die_msg\nIf you want to use a path with a leading dash, please consider adding \`./\` prefix."
                die "$die_msg"
            fi
            DISK_NAME="$2"
            shift
            ;;
        -p|-r)
            if [ -z "$2" ] || ! is_uint "$2"; then
                die "$1 requires an uint argument"
            fi
            case "$1" in
                -p) CPU_COUNT="$2" ;;
                -r) RAM_SIZE="$2" ;;
            esac
            shift
            ;;
    esac
    shift
done

QEMU_ARGS="\\
    -cpu \"$QEMU_CPU\" \\
    -machine \"$QEMU_MACHINE\" \\
    -smp \"$CPU_COUNT\" \\
    -drive \"if=pflash,file=$PRJCT_ROOT/$FW_DIR/$EFI_CODE,format=raw,readonly=on\" \\
    -drive \"if=pflash,file=$PRJCT_ROOT/$FW_DIR/$EFI_VARS,format=raw\" \\
    -drive \"file=$DISK_NAME,if=none,id=drv0,format=raw\" \\
    -device nvme,drive=drv0,serial=unixv11nvme \\
    -device qemu-xhci,id=xhci \\
    -device usb-kbd,bus=xhci.0 \\
    -device usb-mouse,bus=xhci.0 \\
    -m \"${RAM_SIZE}M\" \\
    -serial stdio \\
"

eval "\"$QEMU_SYSTEM\" $QEMU_ARGS" || eval "\"$QEMU_SYSTEM\" $QEMU_ARGS -display none"
