[package]
name = "unix-v11-efi"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "unix-v11-efi"
path = "src/main.rs"
test = false

[dependencies]
uefi = "0.35.0"
xmas-elf = "0.10.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
